### ISSUE TITLE
error showing

### ISSUE THREAD

**Issue by naninaveen9** [Orelsaada/YouTube-Subpals-bot#3]
[0416/191750.201:INFO:CONSOLE(8)] "[iFrameSizer][Host page: zt-popup] IFrame has not responded within 5 seconds. Check iFrameResizer.contentWindow.js has been loaded in iFrame. This message can be ignored if everything is working, or you can set the warningTimeout option to a higher value or zero to suppress this warning.", source: https://www.subpals.com/wp-content/plugins/steempress/public/js/iframeResizer.min.js?ver=5.4 (8)
[0416/191751.322:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://500053.stats.ryzeo.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.", source: https://www.subpals.com/ (0)
[0416/191800.480:INFO:CONSOLE(3)] "Uncaught RangeError: Maximum call stack size exceeded.", source: https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js (3)
[0416/191800.524:INFO:CONSOLE(3)] "Uncaught RangeError: Maximum call stack size exceeded.", source: https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js (3)
[0416/191800.556:INFO:CONSOLE(3)] "Uncaught RangeError: Maximum call stack size exceeded.", source: https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js (3)
Traceback (most recent call last):
  File "n.py", line 41, in <module>
    driver.find_element_by_name('password').send_keys(channel_pass)  # Channel password
  File "C:\Users\guntr\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 496, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "C:\Users\guntr\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\guntr\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\guntr\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="password"]"}
  (Session info: headless chrome=81.0.4044.113)

**Comment by Orelsaada** [comment]
Did you register to subpals manually before running the script?
